### ISSUE TITLE
Add samples for the toolkit

### ISSUE THREAD

**Issue by ankitpas** [IBMStreams/streamsx.sparkMLLib#15]

**Comment by chanskw** [comment]
I tried the sample and it did not work out of the box.

1)  the data file is not in the data directory... so when I tried to run the application, the FileSource cannot find it.
2)  Project does not build out of the box, missing spark libraries
3)  The save to model from the Java model generation code, points to a directory that does not exist... so that does not run
4)  The KMeansModel operator points to a model location that does not exist, so that does not run either.

In general, we need a bit more instructions to get user up and running.. I don't think they will know how to set this up without instructions.

**Comment by joergboe** [comment]
Commit
2ebe4bbbeb54f75e71c87136d85f80de34d318b2
addresses the issues:
1. Data files are now in data
2. The project now has a makefile which makes the spl part of the sample
The java is not necessary any more since a spark model is delivered in the sample in etc directory
The java application can be compiled if the .classpath points to the downloaded libs from the toolkit
3. Corrected
4. Corrected
