### ISSUE TITLE
Provide ability to reload models

### ISSUE THREAD

**Issue by ankitpas** [IBMStreams/streamsx.sparkMLLib#5]
At present, the specified Spark models are loaded when the operator initializes. We should provide a mechanism to reload these models (perhaps through a control port).

**Comment by ddebrunner** [comment]
For new operators I would recommend a control port that uses JSON, rather than trying to have a SPL schema that can handle multiple types of control instructions, using the standard SPL schema

type Json = rstring jsonString

This should also make it able to tie into control variables, including the utilities in the streamsx.plumbing project.
